// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenProject() {
  return window['go']['main']['App']['OpenProject']();
}

export function ReadFileContents(arg1) {
  return window['go']['main']['App']['ReadFileContents'](arg1);
}

export function SaveFileContents(arg1, arg2) {
  return window['go']['main']['App']['SaveFileContents'](arg1, arg2);
}
