// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {project} from '../models';

export function OpenProject():Promise<project.Project>;

export function ReadFileContents(arg1:string):Promise<string>;

export function SaveFileContents(arg1:string,arg2:string):Promise<void>;
